language: node_js
sudo: true
node_js:
  - '4'
  - stable

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: stable
  
install:
  - sudo apt-get install libfontconfig
  - npm install -g npm@latest
  - npm install -g bower
  - npm install -g gulp
  - npm install

before_script:
  - bower install

script:
  - npm test
