language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - stable

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: stable
  
install:
  - npm install -g npm@latest

before_script:
  - npm install -g bower
  - npm install -g gulp

script:
  - npm test
